feat: makefile
fixed scripts -> CLI args are now mandatories for the db script

diff --git a/backup-docker-volumes b/backup-docker-volumes
--- a/backup-docker-volumes
+++ b/backup-docker-volumes
@@ -1,19 +1,62 @@
 #!/usr/bin/env bash
 
+# Script version
+VERSION=0.0.1
+# Script filename
+FILENAME=$(basename $0)
 # Current date
 DATE=$(date "+%Y-%m-%d")
-# Default source point (if there are no CLI arguments)
-DEFAULT_SOURCE_POINTS=( ${HOME} )
 # https://github.com/theobori/dockerv
 #
 # dockerv source points
-SOURCE_POINTS=${@:-${DEFAULT_SOURCE_POINTS[@]}}
+#
+# You can replace $@ by the sources point you want
+# instead of passing CLI arguments
+SOURCE_POINTS=( $@ )
 # Retention days amount
 RETENTION=3
 # Backup directory path
 BACKUP_DIRECTORY="/backup"
 # dockerv destination point
 DESTINATION_POINT="${BACKUP_DIRECTORY}/docker-volumes-${DATE}.tar.gz"
+
+# Help display function
+function print_help() {
+    cat <<EOF
+${FILENAME}
+Version ${VERSION}
+
+Optional arguments
+  -h        Show this help message
+  -v        Print the script version
+
+Usage example
+${FILENAME} src1 src2 src3
+EOF
+}
+
+# Parsing the CLI arguments with the built-in getopts command
+function parse() {
+    while getopts "hv" arg; do
+        case ${arg} in
+            h)
+                print_help
+                exit 0
+                ;;
+
+            v)
+                echo ${FILENAME} -- ${VERSION}
+                exit 0
+                ;;
+        esac
+    done
+
+    if [[ ${#SOURCE_POINTS[@]} -eq 0 ]]
+    then
+        echo "Missing sources, check the help message" >&2
+        return 1
+    fi
+}
 
 # Exporting and packing Docker volumes
 # selected with the source points as a Tarball
@@ -24,10 +67,13 @@ function export_docker_volumes() {
         args+="--src \"${source_point}\" "
     done
 
-    dockerv export \
+    if ! dockerv export \
         ${args} \
         --dest ${DESTINATION_POINT} \
         --force
+    then
+        return 1
+    fi
 }
 
 # Deleting files older than ${RETENTION} days
@@ -39,10 +85,12 @@ function purge_backups() {
 }
 
 function main() {
+    parse $@ || exit 1
+
     test -d ${BACKUP_DIRECTORY} || mkdir -p ${BACKUP_DIRECTORY}
 
     export_docker_volumes || exit 1
     purge_backups
 }
 
-main
+main $@
